security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # Use "username" if it's the identifier
        # used to reload user from session & other features (e.g. switch_user)



    firewalls:
        main:
            pattern: ^/

            logout:
                path: app_logout
                invalidate_session: true
                target: /login
            custom_authenticator: App\Security\UserAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

